### ISSUE TITLE
icon-size = "medium" doesn't work maybe

### ISSUE THREAD

**Issue by Liqiuyue9597** [luyilin/vue-cute-timeline#16]
`<timeline-item bg-color="#E6B6E0" icon-size="medium">学习</timeline-item>`
`icon-size` doesn't work

**Comment by luyilin** [comment]
![image](https://user-images.githubusercontent.com/12069729/86696196-d0656500-c03f-11ea-933e-b84fe8f22267.png)
It works for me, maybe you could try the demo at example/App.vue?

**Comment by faf-xff** [comment]
我也有这个问题，

**Comment by luyilin** [comment]
emm奇怪，可以提供个demo吗？

**Comment by chemeng** [comment]
I think your npm package code doesn't include the iconSizeData assignment for some reason

**Comment by luyilin** [comment]
Have updated the config file and published the newest package to include the `iconSize` prop, please reinstall `vue-cute-timeline` by running `npm i vue-cute-timeline@latest -S` to fix this issue.
By the way, met some problem when injecting css in js and not sure why. Need to import the css file manually now emmm. Have updated the usage as well.
