### ISSUE TITLE
Better to support adding timestamp on the left side.

### ISSUE THREAD

**Issue by tomdong** [luyilin/vue-cute-timeline#4]
it would be clear to have timestamp on one side and have evevt detail on the other side.

**Comment by luyilin** [comment]
The original intention of the design is to make a visual connection of vertical displayed timeline. You can set custom content of timeline, including timestamp, like this 
![2018-02-23 10 19 23](https://user-images.githubusercontent.com/12069729/36575139-3a745d68-1884-11e8-889c-f3d3e3722577.png)

And I fully understand what you mean, [vue-light-timeline](https://github.com/SME-FE/vue-light-timeline) maybe a better choice for you 😄 Maybe there is no need to reinvent the wheel.

**Comment by tomdong** [comment]
OK, got that!
You are right. (•̀⌄•́)
