### ISSUE TITLE
Hollow doesn't really work on dark background timeline

### ISSUE THREAD

**Issue by mayashavin** [luyilin/vue-cute-timeline#8]
In case timeline circle is hollow, it is created by default with the following background
`background: rgb(255, 255, 255)`  besides the custom border color. If timeline has dark background, this timeline circle will look like whole circle (not hollow). 
See attached screenshot (See item 2)
<img width="384" alt="screen shot 2018-09-26 at 20 45 33" src="https://user-images.githubusercontent.com/6650139/46098478-2d768a80-c1cd-11e8-8195-bc5436021452.png">
Would suggest to allow user to decide what background theme separately. If no one is working on this issue, I can submit a pull request :)

**Comment by luyilin** [comment]
Sorry to get back to you so late. 
At first I set the default white background color to not show line inside circle roughly. The design is bad, thanks to point out the problem and pr welcome ☺️

**Comment by luyilin** [comment]
published on v1.2.8 
thanks a lot for your work 👍
