### ISSUE TITLE
动态渲染数据数据结构问题

### ISSUE THREAD

**Issue by LeeAli** [luyilin/vue-cute-timeline#9]
我发现右边数据如果按照年份来聚合的话,
<pre>
<code>
ul
h3
li
ul
</code>
</pre>
不太合理,或许使用下面的结构更合适一点,,对作用域中也更友好一点
<pre>
<code>
ul
li
ul/ul
li
ul
</code>
</pre>

**Comment by luyilin** [comment]
我查了下资料 li 标签可以包含 div 以及 ul，ul 的子元素应该只有 li，所以在 ul 标签里嵌套 h3 标签是不规范的，而把 h3 标签改成 ul 也不是很合适，因为 h3 标签里还有 div，所以我改成了 li 标签，欢迎 review～
